/** Startlijst voor de masterlijst: eenmalig gemaakt uit de Excel 'Paklijst'
 *  (de blokken per persoon en per soort spullen, plus de tabbladen 'Wat waar'
 *  en 'Aan te schaffen'). De reistypes en plekken zijn een eerste inschatting;
 *  pas ze in de app aan. Items met `kinds: []` staan alleen op de aanschaflijst. */
import type { PackItem } from './types';

export const PACKLIST_SEED: Array<Omit<PackItem, 'id'>> = [
  {"name": "Tent", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Karretje (los)"},
  {"name": "Tentstokken", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Karretje (los)"},
  {"name": "Haringen", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat tentspullen"},
  {"name": "Scheerlijnen etc.", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat snoeren & overig"},
  {"name": "Zeilen", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat zeilen"},
  {"name": "Grondzeil", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer", "toBuy": true},
  {"name": "Inloopmatten", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Gasstel", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat kookstel"},
  {"name": "Gastank", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat kookstel"},
  {"name": "Verlengsnoer", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat snoeren & overig", "toBuy": true},
  {"name": "Eurostekker", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat snoeren & overig"},
  {"name": "Stekkerdoos", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat snoeren & overig"},
  {"name": "Zaklamp", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Gereedschap", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "toBuy": true, "note": "Twijfel: nog beslissen"},
  {"name": "Rubberen hamer", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Kastje kookstel", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Auto"},
  {"name": "Emmer", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Toiletrol", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Medicijndoos", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "toBuy": true},
  {"name": "Koelkast", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Auto"},
  {"name": "Fleecedeken", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Rol vuilniszakken", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Wasknijpers", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "toBuy": true},
  {"name": "Waslijn", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Waspoeder", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Stoov", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Luchtbed", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Pomp", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Hoeslaken", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Slaapzak matthijs", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Matje matthijs", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Tentje Amelie", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Tentje Lotte", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Slaapzakken", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Kussens", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Stoelen", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Auto"},
  {"name": "Krukje", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "toBuy": true},
  {"name": "Kinderstoeltjes", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Babystoel", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Tafel", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Auto"},
  {"name": "Tafelkast", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Auto"},
  {"name": "Picknickkleed", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Bezem", "group": "tent", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer", "toBuy": true},
  {"name": "Borden", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Bakjes", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Bestek", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Snijplanken", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Zakmes", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Pannenset", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Blikopener", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken", "toBuy": true},
  {"name": "Kurkentrekker", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken", "toBuy": true},
  {"name": "Snijmessen", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken", "toBuy": true},
  {"name": "Spatels", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Aansteker", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Opscheplepel", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Perculator", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Fluitketel", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Kruidencarrousel", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Schaar", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Onderzetter", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Afwasborstel", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Afwasmiddel", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Koffie", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Thee", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Olijfolie", "group": "servies", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Krat servies & koken"},
  {"name": "Lange Pyjama", "group": "matthijs", "qty": 2, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Korte pyjama", "group": "matthijs", "qty": 2, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Korte broek", "group": "matthijs", "qty": 6, "scales": true, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Lange broek", "group": "matthijs", "qty": 2, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Onderbroek", "group": "matthijs", "qty": 12, "scales": true, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Hemden", "group": "matthijs", "qty": 12, "scales": true, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Sokken", "group": "matthijs", "qty": 6, "scales": true, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Shirt", "group": "matthijs", "qty": 10, "scales": true, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Trui", "group": "matthijs", "qty": 4, "scales": true, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Zwembroek", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Matthijs"},
  {"name": "Zwemshirt", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Matthijs"},
  {"name": "Buitenvest", "group": "matthijs", "qty": 2, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Matthijs"},
  {"name": "Jas", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Buitenspeelpak/broek", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Matthijs"},
  {"name": "Joggingbroek", "group": "matthijs", "qty": 2, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Sandalen", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Schoenen", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Laarzen", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Matthijs"},
  {"name": "Pet", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Zonnebril", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Kussen", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Tas Matthijs"},
  {"name": "Zwempakje", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Matthijs"},
  {"name": "Toilettas", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Tandenborstel", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Tandpasta", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Shampoo", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Gel", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Zonnebrandcreme kinderen", "group": "matthijs", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Matthijs"},
  {"name": "Lange Pyjama", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Korte pyjama", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Korte broek", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Lange broek", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Onderbroeken", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Hemdjes", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Sokken", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Shirts", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Truien", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Zwembroek", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Amélie"},
  {"name": "Zwemshirt", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Amélie"},
  {"name": "Buitenvest", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Amélie"},
  {"name": "Jas", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Buitenspeelbroek", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Amélie"},
  {"name": "Sandalen", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Schoenen", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Laarzen", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Amélie"},
  {"name": "Pet", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Zonnebril", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Knuffels", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Zwembandjes", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Amélie"},
  {"name": "Luiers", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Toilettas", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Tandenborstel", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Tandpasta", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Sudocreme", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Shampoo", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Douchegel", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Borstel+elastiekjes", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Nagelsetje", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Flesjes", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Melkpoeder", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Vitamine D", "group": "amelie", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Amélie"},
  {"name": "Aankleedkussen", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Wipstoel", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Draagdoek", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Draagzak", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Wandelwagen", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Zwemband baby", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"]},
  {"name": "Vitamine D", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Vitamine K", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Lepel", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Luiers", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Rompers", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Broeken", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Shirts", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Trui/jas", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Muts", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Zonnehoedje", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Sokken", "group": "lotte", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Iphone lader", "group": "irene", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Irene"},
  {"name": "Hardloopschoenen", "group": "irene", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Irene"},
  {"name": "Hardloopkleren", "group": "irene", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Irene"},
  {"name": "Iphone lader", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Sokken", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Onderbroeken", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Zwembroek", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Niels"},
  {"name": "Lange broek", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Korte broek", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Shirts", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Truien/vesten", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Zonnebril", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Pet", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Handdoeken", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Washandje", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Regenjas", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Hardloopschoenen", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Niels"},
  {"name": "Hardloopkleren", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Tas Niels"},
  {"name": "Toilettas", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Tandenborstel", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Lader", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Shampoo", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Gel", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Deo", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Lenzenvloeistof", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Lenzendoosje", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Reservelenzen", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Daglenzen", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Tandpasta", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Zonnebrandcreme", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Aftersun", "group": "niels", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Tas Niels"},
  {"name": "Badhanddoek irene", "group": "handdoeken", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"]},
  {"name": "Badhanddoek niels", "group": "handdoeken", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"]},
  {"name": "Badhanddoek amelie", "group": "handdoeken", "qty": 2, "scales": false, "kinds": ["kamperen", "huisje"]},
  {"name": "Badhanddoek matthijs", "group": "handdoeken", "qty": 2, "scales": false, "kinds": ["kamperen", "huisje"]},
  {"name": "Grote hydrofiel doeken", "group": "handdoeken", "qty": 6, "scales": true, "kinds": ["kamperen", "huisje"]},
  {"name": "Kleine hydrofieldoeken", "group": "handdoeken", "qty": 10, "scales": true, "kinds": ["kamperen", "huisje"]},
  {"name": "Handdoeken N+I", "group": "handdoeken", "qty": 4, "scales": false, "kinds": ["kamperen", "huisje"]},
  {"name": "Washandjes kinderen", "group": "handdoeken", "qty": 8, "scales": true, "kinds": ["kamperen", "huisje"]},
  {"name": "Washandjes (N+I)", "group": "handdoeken", "qty": 4, "scales": true, "kinds": ["kamperen", "huisje"]},
  {"name": "Theedoeken", "group": "handdoeken", "qty": 8, "scales": true, "kinds": ["kamperen", "huisje"]},
  {"name": "Vaatdoekjes", "group": "handdoeken", "qty": 8, "scales": true, "kinds": ["kamperen", "huisje"]},
  {"name": "Muziekboxje + oplader", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Spelletjes", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Krat speelgoed"},
  {"name": "Boeken", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Puzzelboeken", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Schrijfgerei", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Kruiken", "group": "overig", "qty": 4, "scales": false, "kinds": ["kamperen"]},
  {"name": "Speelgoed", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Krat speelgoed"},
  {"name": "Kleurboek", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Krat speelgoed"},
  {"name": "Stiften", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Krat speelgoed"},
  {"name": "Puzzel", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Krat speelgoed"},
  {"name": "Kinderspelletjes", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"], "location": "Krat speelgoed"},
  {"name": "Speelkleed", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Strandbal", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Vakantieboek", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"]},
  {"name": "Rugzak", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "location": "Karretje (los)"},
  {"name": "Paspoorten", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "abroadOnly": true},
  {"name": "Creditcard", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "abroadOnly": true},
  {"name": "Anwb pas", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje", "logeren"], "abroadOnly": true},
  {"name": "Bandenplakset", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Fietspomp", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Muggenspray", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen", "huisje"]},
  {"name": "Fiets matthijs", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Fietsen op karretje"},
  {"name": "Fiets niels", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Fietsen op karretje"},
  {"name": "Fiets irene", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Fietsen op karretje"},
  {"name": "Loopfiets amelie", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Step amelie", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"]},
  {"name": "Fietskar", "group": "overig", "qty": 1, "scales": false, "kinds": ["kamperen"], "location": "Dakkoffer"},
  {"name": "Bestekdoos", "group": "servies", "qty": 1, "scales": false, "kinds": [], "toBuy": true},
  {"name": "Opvouwbare emmer", "group": "tent", "qty": 1, "scales": false, "kinds": [], "toBuy": true},
  {"name": "Jerrycan", "group": "tent", "qty": 1, "scales": false, "kinds": [], "toBuy": true, "note": "Twijfel: nog beslissen"},
  {"name": "Opbergkastje", "group": "tent", "qty": 1, "scales": false, "kinds": [], "toBuy": true, "link": "https://www.obelink.nl/obelink-nancy-kast-704303.html"},
  {"name": "Verlichting", "group": "tent", "qty": 1, "scales": false, "kinds": [], "toBuy": true},
  {"name": "Aanhanger", "group": "overig", "qty": 1, "scales": false, "kinds": [], "toBuy": true, "note": "Wens: grotere aanhanger"},
];
